server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  quartz:     # quartz任务配置
    job-store-type: jdbc    # 存储方式，这里使用数据库存储quartz任务信息
    properties:
      org.quartz.scheduler.instanceName: clusteredScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.tablePrefix: QRTZ_    # quartz表前缀
      org.quartz.jobStore.isClustered: true     # 打开集群配置
      org.quartz.jobStore.clusterCheckinInterval: 2000    # 设置集群检查间隔20s
      org.quartz.jobStore.useProperties: false
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 10
      org.quartz.threadPool.threadPriority: 5
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true

