server:
  port: 9090
  servlet:
    context-path: /
spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /   #rabbitmq虚拟主机
    connection-timeout: 15000 #超时设置
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123
#mybatis:
#  type-aliases-package: com.xue.demo
#  mapper-locations: classpath:com/xue/demo/mapping/*.xml

#logging:
#  level:
#    root: debug