server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test01?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123