server:
  port: 9091
  servlet:
    context-path: /
spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /   #rabbitmq虚拟主机
    connection-timeout: 15000 #超时设置
    listener:
      simple:
        concurrency: 5 #并发数
        acknowledge-mode: manual #设置签收模式，这里设置成手工签收
        max-concurrency: 10 #最大并发数
        prefetch: 1 #消息限流，这里设置为1条消息
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null