server:
  port: 8080
spring:
  datasource:
    druid:    # 使用ali的druid数据源（还可用于监控、过滤filter）
      url: jdbc:mysql://localhost:3306/test01?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123
#    url: jdbc:mysql://localhost:3306/test01?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0   #设置数据库索引为0，默认为0
    password:     #没有密码，不设置
    jedis:
      pool:
        max-active: 1000    #连接池最大连接数
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接
        min-idle: 2     # 连接池中的最小空闲连接
    timeout: 2000       # 连接超时时间（毫秒）
mybatis:
  mapper-locations: classpath:mapper/*.xml    # 显式指定mapper文件路径